---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hypriot-http
  labels:
    app: hypriot-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hypriot-http
  template:
    metadata:
      labels:
        app: hypriot-http
        version: v1
    spec:
      containers:
      - name: hypriot-http
        image: hypriot/rpi-busybox-httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hypriot-http
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: hypriot-http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hypriot-http
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: hypriot-http.pi
    http:
      paths:
      - path: /
        backend:
          serviceName: hypriot-http
          servicePort: http
