apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hypriot
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: hypriot.pi
    http:
      paths:
      - path: /
        backend:
          serviceName: hypriot
          servicePort: 80
