apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-node
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: hello-node.pi
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-node
          servicePort: 8080
